name: 'Generate Image'
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(cat VERSION)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: parasrah/nerves_system_rpi3/buildroots
          username: parasrah
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }}"


