name: 'Generate Releases'
on:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(cat VERSION)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: parasrah/nerves_system_rpi3/buildroots
          username: parasrah
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }},${{ env.GITHUB_SHA }}"

  system:
    needs: docker
    container:
      image: "docker.pkg.github.com/parasrah/buildroots:${{ env.GITHUB_SHA }}"
      volumes:
        - /home/br-user/app:/volume_mount
    steps:
      - uses: actions/checkout@master
      - name: Get dependencies
        run: mix deps.get
      - name: Build system
        run: mix compile
